### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by retrokiller543** [DV1512/backend#7]
# Documentation

This issue will hold the disscusion for which documentation tool we will use when developing the api.

The current example implementations that are on the table to use are the following:

| Crate | usability | custimizable |
|--------|--------|--------|
| [apistos](https://github.com/netwo-io/apistos/tree/main) | 6/10 | 4/10 |
| [utoipa](https://github.com/juhaku/utoipa/tree/master) | 5/10 | 8/10 | 

Both options are valid and works but there are quite large drawbacks to each of them.

### [apistos](https://github.com/netwo-io/apistos/tree/main)

- Overrites the `actix` App builder making macros for constructing the method and path easier no longer works and we need to manually build the paths and define methods, this is a minor thing but is annoying.
- No way of setting example responses, only thing we can do is to describe the endpoints.
- Hard to register the Swagger endpoint
- Poor documentation

### [utoipa](https://github.com/juhaku/utoipa/tree/master)

- A lot of boilerplate code is required for this to work, this includes on every DTO we have, request and response.
- No way of auto registering endpoints, only thing we can do is to nest multiple "`ApiDocs`" inside each other to avoid having a extremely large macro.

### [apistos](https://github.com/netwo-io/apistos/tree/main)

- Simple to use
- Auto registers the endpoints based our current way of registering the endpoints to `actix` meaning we dont need to reregister them

### [utoipa](https://github.com/juhaku/utoipa/tree/master)

- Loads of things to change how the docs are generated, request examples, response examples, etc.
- Easy way to register the swagger endpoint with a single line.

**Comment by kebabohvo** [comment]
After looking at this, I feel more inclined towards Utopia, it seems to have more documentation about it.
+1 vote for Utopia from Oskar
